<a href="https://colab.research.google.com/github/elhamod/IS834_Fall_2026/blob/main/Session%2003%20-%20Pandas%20I%20-%20Importing%20and%20Exploration/03_Analytics_with_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# IS834 — Session 3

Work through this notebook in Colab. The lecture cells are filled in and ready to run; the
**Exercises** are yours to complete — write your code in the `# Your code here` cells and your
reasoning in the `*Provide your answer here*` cells.

Every dataset is read straight from the course repository, so there is nothing to upload or install.

*Adapted from Brock Tibert's IS834 Fall 2025 session 3. Edited for Fall 2026 by Mohannad Elhamod.*

# Learning Goals

- Loading datasets into pandas
- Inspection and review
- Column summaries
- Unique values and value counts
- Selecting rows and columns
- Sorting

Cleaning the problems we find along the way is next session's job.

# Warmup Exercises

A quick check on last week's fundamentals before we open a dataset.

**Exercise 1.** Return all of the elements from `mylist` except `apple`.

In [1]:
# Your code here
mylist = ['apple', 'banana', 'cherry']
x = []
for i in mylist:
    if i != 'apple':
        x.append(i)
print(x)

['banana', 'cherry']

In [1]:
mylist = ['apple', 'banana', 'cherry']
y = [i for i in mylist if i != 'apple']
print(y)

['banana', 'cherry']

**Answer**

*Provide your answer here*

**Exercise 2.** Use `mylist` from above, and add strawberries to the list.

In [5]:
# Your code here
mylist.append('strawberry')
print(mylist)

['apple', 'banana', 'cherry', 'strawberry']

**Answer**

*Provide your answer here*

**Exercise 3.** For the dictionary below, do the following:

- a) identify all of the keys
- b) access the key `Salary`
- c) delete the key `Employee_ID`

In [ ]:
# Your code here -- a) list the keys

In [ ]:
# Your code here -- b) access the Salary key

In [ ]:
# Your code here -- c) delete the Employee_ID key

**Answer**

*Provide your answer here*

# Getting Started

Let's look at the dataset. It is a small survey extract, `sample-survey-data.csv`, which the next cell reads straight from the course repository.


###  Data Roles/Types

![](https://cdn1.byjus.com/wp-content/uploads/2021/12/Types-of-Data-in-Statistics.png)

Notes:

- Nominal data doesn't have an ordering (East, West regions), whereas Ordinal data retains a sorting (bronze, silver, gold).
- Discrete are data are countable values (# of rooms in a home).  Continuous can take on any value, and usually come from measurements (time to run a marathon, closing price of a stock).

**Question 1.** Data stored as a number is not always a quantity. Can you think of columns that arrive as numbers but are really labels?

**Answer**

*Provide your answer here*

### Dataset Structure



![](https://media.geeksforgeeks.org/wp-content/cdn-uploads/creating_dataframe1.png)

# pandas 101

## Ingestion

In [49]:
# pandas is pre-installed on Colab, so it only needs importing. "as pd" is the universal convention.
import pandas as pd

# Every data file this notebook uses is read straight from the course repository.
# There is nothing to upload: DATA is the folder those files live in.
DATA = "https://raw.githubusercontent.com/laglead/IS834_Fall_2026/main/data/"

In [50]:
# Read the survey data from the CSV that ships with this notebook.
# The survey file is read straight from the course repository -- nothing to upload.
df = pd.read_csv(DATA + "sample-survey-data.csv")

In [51]:
# A quick look at the first rows -- we will come back to inspection properly later in class.
df.head(3)

,id,Age,userid,Income,Education,Satisfaction,Recommend,Region,Signup Date,comment
0,1,23.0,user1,35000,Bachelor,4.0,Yes,Northeast,2025-05-01,Absolutely fantastic service — I am extremely ...
1,2,45.0,user2,-68000,Master,5.0,Yes,Midwest,2024-05-03,The product quality is excellent and the exper...
2,3,31.0,user3,42000,Associate,3.0,No,South,2024-04-09,I really enjoyed the fast delivery and friendl...

Let's see a variety of the ways to save and read data via pandas (Image taken form: https://levelup.gitconnected.com/pandas-complete-guide-fba59b69598c).

![](https://snipboard.io/dkbpF0.jpg)


> worth nothing above assumes that pandas is imported as pd, and the dataframe you want to export is `df` in your session.

In [52]:
# Another csv, this time a plain file, read the same way from the course repository.
nvda = pd.read_csv(DATA + "nvda.csv")

type(nvda)

pandas.DataFrame

![](https://images.ctfassets.net/lzny33ho1g45/1axzhgm4thtZi42OxsNeZk/8414378ccb84bbb5586dc9f56315731c/Google_Sheets_vs_Excel_hero.jpg?fm=jpg&q=31&fit=thumb&w=800&h=300)

Documentation: https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html

In [53]:
# Excel works the same way. Colab already has openpyxl, the library pandas uses to open .xlsx files.
xl = pd.read_excel(DATA + 'sales.xlsx')

xl.head(3)

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,...,Central,Illinois,Addison,60101,2012-05-28,2012-05-30,1.32,2,5.90,88525
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2010-07-07,2010-07-08,4.56,4,13.01,88522
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.64,7,49.92,88523

In [54]:
# But that workbook has three worksheets! sheet_name=None reads them ALL and returns a dictionary.
wb = pd.read_excel(DATA + 'sales.xlsx', sheet_name="Returns") #1st sheet if sheet_name is not declared

type(wb)
wb.head()

   Order ID    Status
0        65  Returned
1       612  Returned
2       614  Returned
3       678  Returned
4       710  Returned

# Follow up Questions and Exercises — Part 1: loading data

**Exercise 4.** Review the keys of the dictionary that `pd.read_excel(..., sheet_name=None)` returned.

In [ ]:
# Your code here

**Answer**

*Provide your answer here*

**Exercise 5.** Based on what you know about dictionaries, experiment! Can you create a variable called `users` that is a pandas DataFrame?

> HINT: Remember that dictionaries in python are key:value/object pairs.

In [ ]:
# Your code here

**Answer**

*Provide your answer here*

## Inspection

In [55]:
# Back to the small survey dataset.
df.head(7)

,id,Age,userid,Income,Education,Satisfaction,Recommend,Region,Signup Date,comment
0,1,23.0,user1,35000,Bachelor,4.0,Yes,Northeast,2025-05-01,Absolutely fantastic service — I am extremely ...
1,2,45.0,user2,-68000,Master,5.0,Yes,Midwest,2024-05-03,The product quality is excellent and the exper...
2,3,31.0,user3,42000,Associate,3.0,No,South,2024-04-09,I really enjoyed the fast delivery and friendl...
3,4,52.0,user4,91000,Doctorate,4.0,Yes,West,2025-01-02,"Overall a good experience, though a few minor ..."
4,4,52.0,user4,91000,Doctorate,4.0,Yes,West,2025-01-02,"The product works fine, but I am slightly disa..."
5,5,27.0,user5,50000,Bachelor,NaN,no,Northeast,2024-11-12,"It was okay — not amazing, not terrible, just ..."
6,6,38.0,user6,60000,Master,5.0,Yes,South,2023-05-14,"I am unhappy with the slow shipping, but custo..."

Important considerations

- Python is 0-based
- pandas thinks in rows/columns.  We will start to break that concept down with commands.
- A column of data is mapped to a single data type. All values must be strings, or numbers.  If the data are mixed, all data are `cast` to  one data type.
- The numbers along the rows are referred to as the row index.
- Columns can/usually have names, and this is also an index. It's a column index.

In [56]:
# .shape reports (number of rows, number of columns) -- the first thing to check after any load.
df.shape

(12, 10)

In [57]:
# The column names live in their own index object.
df.columns

Index(['id', 'Age', 'userid', 'Income', 'Education', 'Satisfaction',
       'Recommend', 'Region', 'Signup Date', 'comment'],
      dtype='str')

In [59]:
# .to_list() turns them into a plain Python list, which is easier to work with.
df.columns.to_list()

['id',
 'Age',
 'userid',
 'Income',
 'Education',
 'Satisfaction',
 'Recommend',
 'Region',
 'Signup Date',
 'comment']

In [60]:
# A neat trick: "in" asks whether a column exists, and it is case sensitive.
print('Region' in df.columns)
print('education' in df.columns)   # False -- the column is spelled Education

True
False

In [61]:
# .info() gives the columns, their types, and how many non-missing values each one holds.
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            12 non-null     int64
 1   Age           11 non-null     float64
 2   userid        12 non-null     str
 3   Income        12 non-null     int64
 4   Education     12 non-null     str
 5   Satisfaction  11 non-null     float64
 6   Recommend     11 non-null     str
 7   Region        11 non-null     str
 8   Signup Date   12 non-null     str
 9   comment       12 non-null     str
dtypes: float64(2), int64(2), str(6)
memory usage: 1.1 KB

In [62]:
# .tail() shows the end of the data, which often looks different from the start.
df.tail(3)

,id,Age,userid,Income,Education,Satisfaction,Recommend,Region,Signup Date,comment
9,9,NaN,user9,56000,Bachelor,2.0,No,NaN,2023-10-01,The service was terrible and the support team ...
10,10,148.0,user10,80000,Master,5.0,Yes,South,2025-04-12,I am extremely dissatisfied and very disappoin...
11,11,25.0,user3,78643,High School,2.0,No,North,2026-02-10,This was the worst experience I’ve ever had — ...

In [63]:
# head(20) on a 12-row dataset simply shows everything.
df.head(20)

,id,Age,userid,Income,Education,Satisfaction,Recommend,Region,Signup Date,comment
0,1,23.0,user1,35000,Bachelor,4.0,Yes,Northeast,2025-05-01,Absolutely fantastic service — I am extremely ...
1,2,45.0,user2,-68000,Master,5.0,Yes,Midwest,2024-05-03,The product quality is excellent and the exper...
2,3,31.0,user3,42000,Associate,3.0,No,South,2024-04-09,I really enjoyed the fast delivery and friendl...
3,4,52.0,user4,91000,Doctorate,4.0,Yes,West,2025-01-02,"Overall a good experience, though a few minor ..."
4,4,52.0,user4,91000,Doctorate,4.0,Yes,West,2025-01-02,"The product works fine, but I am slightly disa..."
5,5,27.0,user5,50000,Bachelor,NaN,no,Northeast,2024-11-12,"It was okay — not amazing, not terrible, just ..."
6,6,38.0,user6,60000,Master,5.0,Yes,South,2023-05-14,"I am unhappy with the slow shipping, but custo..."
7,7,41.0,user7,72000,Bachelor,3.0,No,Midwest,2024-12-10,The experience was frustrating and somewhat di...
8,8,29.0,user8,40000,High School,4.0,NaN,West,2024-09-27,Very poor quality — I regret buying this produ...
9,9,NaN,user9,56000,Bachelor,2.0,No,NaN,2023-10-01,The service was terrible and the support team ...
10,10,148.0,user10,80000,Master,5.0,Yes,South,2025-04-12,I am extremely dissatisfied and very disappoin...
11,11,25.0,user3,78643,High School,2.0,No,North,2026-02-10,This was the worst experience I’ve ever had — ...

> Read down the Dtype column and note which columns pandas is treating as numbers and which it is not. The exact label it prints for a text column depends on the version of pandas you are running, so read what is on your own screen rather than memorising a name.

Now lets look at the output of info one more time

In [35]:
# Read the Non-Null Count column: any number below the row count means missing values.
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            12 non-null     int64
 1   Age           11 non-null     float64
 2   userid        12 non-null     str
 3   Income        12 non-null     int64
 4   Education     12 non-null     str
 5   Satisfaction  11 non-null     float64
 6   Recommend     11 non-null     str
 7   Region        11 non-null     str
 8   Signup Date   12 non-null     str
 9   comment       12 non-null     str
dtypes: float64(2), int64(2), str(6)
memory usage: 1.1 KB

We can see that the shape exists, 12 entries, 10 columns, but based on the Non-Null column, some rows have missing data

In [64]:
# Sorting is usually a reporting step, done after summarizing -- but it is also a fast way to spot bad values.
df.sort_values('Age').head(20)

,id,Age,userid,Income,Education,Satisfaction,Recommend,Region,Signup Date,comment
0,1,23.0,user1,35000,Bachelor,4.0,Yes,Northeast,2025-05-01,Absolutely fantastic service — I am extremely ...
11,11,25.0,user3,78643,High School,2.0,No,North,2026-02-10,This was the worst experience I’ve ever had — ...
5,5,27.0,user5,50000,Bachelor,NaN,no,Northeast,2024-11-12,"It was okay — not amazing, not terrible, just ..."
8,8,29.0,user8,40000,High School,4.0,NaN,West,2024-09-27,Very poor quality — I regret buying this produ...
2,3,31.0,user3,42000,Associate,3.0,No,South,2024-04-09,I really enjoyed the fast delivery and friendl...
6,6,38.0,user6,60000,Master,5.0,Yes,South,2023-05-14,"I am unhappy with the slow shipping, but custo..."
7,7,41.0,user7,72000,Bachelor,3.0,No,Midwest,2024-12-10,The experience was frustrating and somewhat di...
1,2,45.0,user2,-68000,Master,5.0,Yes,Midwest,2024-05-03,The product quality is excellent and the exper...
4,4,52.0,user4,91000,Doctorate,4.0,Yes,West,2025-01-02,"The product works fine, but I am slightly disa..."
3,4,52.0,user4,91000,Doctorate,4.0,Yes,West,2025-01-02,"Overall a good experience, though a few minor ..."
10,10,148.0,user10,80000,Master,5.0,Yes,South,2025-04-12,I am extremely dissatisfied and very disappoin...
9,9,NaN,user9,56000,Bachelor,2.0,No,NaN,2023-10-01,The service was terrible and the support team ...

In [65]:
# ascending=False flips it. An Age of 148 at the top is the kind of thing sorting is for.
df.sort_values('Age', ascending=False).head(20)

,id,Age,userid,Income,Education,Satisfaction,Recommend,Region,Signup Date,comment
10,10,148.0,user10,80000,Master,5.0,Yes,South,2025-04-12,I am extremely dissatisfied and very disappoin...
3,4,52.0,user4,91000,Doctorate,4.0,Yes,West,2025-01-02,"Overall a good experience, though a few minor ..."
4,4,52.0,user4,91000,Doctorate,4.0,Yes,West,2025-01-02,"The product works fine, but I am slightly disa..."
1,2,45.0,user2,-68000,Master,5.0,Yes,Midwest,2024-05-03,The product quality is excellent and the exper...
7,7,41.0,user7,72000,Bachelor,3.0,No,Midwest,2024-12-10,The experience was frustrating and somewhat di...
6,6,38.0,user6,60000,Master,5.0,Yes,South,2023-05-14,"I am unhappy with the slow shipping, but custo..."
2,3,31.0,user3,42000,Associate,3.0,No,South,2024-04-09,I really enjoyed the fast delivery and friendl...
8,8,29.0,user8,40000,High School,4.0,NaN,West,2024-09-27,Very poor quality — I regret buying this produ...
5,5,27.0,user5,50000,Bachelor,NaN,no,Northeast,2024-11-12,"It was okay — not amazing, not terrible, just ..."
11,11,25.0,user3,78643,High School,2.0,No,North,2026-02-10,This was the worst experience I’ve ever had — ...
0,1,23.0,user1,35000,Bachelor,4.0,Yes,Northeast,2025-05-01,Absolutely fantastic service — I am extremely ...
9,9,NaN,user9,56000,Bachelor,2.0,No,NaN,2023-10-01,The service was terrible and the support team ...

> Sorting does not change `df`. Every one of these commands returns a *new* DataFrame and leaves the original alone, which is why we can keep calling `df` and get the original order back.

# Follow up Questions and Exercises — Part 2: inspection

**Exercise 6.** Use the NVIDIA dataset. How many rows and columns are there?

In [73]:
# Your code here
nvidia = pd.read_csv(DATA + "nvda.csv")
nvidia.head()
nvidia.shape
nvidia.describe(include='all')

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
count,1256,1256.000000,1256.000000,1256.000000,1256.000000,1.256000e+03,1256.000000,1256.000000
unique,1256,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,2020-09-18 00:00:00-04:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,57.275551,58.275602,56.167898,57.282980,4.049751e+08,0.000092,0.011146
std,NaN,50.687969,51.432671,49.775996,50.657163,1.803239e+08,0.000805,0.303819
min,NaN,10.957835,11.720920,10.800024,11.213527,4.930821e+07,0.000000,0.000000
25%,NaN,17.205586,17.667084,16.828680,17.224944,2.586050e+08,0.000000,0.000000
50%,NaN,28.738217,29.143904,28.050744,28.875112,3.891296e+08,0.000000,0.000000
75%,NaN,104.514346,107.779875,101.692206,105.240814,5.139898e+08,0.000000,0.000000
max,NaN,182.949688,184.469591,180.579807,183.149673,1.543911e+09,0.010000,10.000000

**Answer**

*Provide your answer here*

**Exercise 7.** List out the column names as a Python list.

In [ ]:
# Your code here

**Answer**

*Provide your answer here*

**Exercise 8.** Sort the data descending by closing price and show the 5 largest values.

In [ ]:
# Your code here

**Answer**

*Provide your answer here*

**Exercise 9.** Print out the info of the dataset. As an analyst, is there anything about how pandas is storing the data that we might want to change or enhance? TRICKY!

In [ ]:
# Your code here -- step 1: print the info for the dataset

In [ ]:
# Your code here -- step 2: fix whatever the Dtype column reveals

**Answer**

*Provide your answer here*

## Summaries and Basic Aggregations

In [ ]:
# .describe() is the fastest way to see the shape of every numeric column at once.
df.describe()

**Question 2.** Take two minutes on the `.describe()` output above. What do you notice about the data it returned -- and about the data it did *not* return?

**Answer**

*Provide your answer here*

In [ ]:
# include="all" adds the text columns, with count/unique/top/freq instead of means.
df.describe(include="all")

In [ ]:
# .T transposes the summary, which is easier to read once you have more than a few columns.
df.describe().T

![](https://miro.medium.com/v2/resize:fit:1400/1*RZ1nbLkRCn-8Hu7DK3I4jA.png)

- A Series is just a name for a column of data in pandas
- Often times we do not have to worry about creating them by hand, as the `pd.read_*` utilties will handle this for us.
- Think of a Series as a list, which is the `value` of a Python dictionary.

In [74]:
# A single column of a DataFrame is a Series -- the DataFrame is the table, the Series is one column of it.
age = df['Age']

print(type(age))
age.head(3)

<class 'pandas.Series'>

0    23.0
1    45.0
2    31.0
Name: Age, dtype: float64

In [75]:
# In practice we rarely want the column itself; we want a number that summarizes it.
df['Age'].mean()

np.float64(46.45454545454545)

In [ ]:
# By default the mean ignores missing values. skipna=False refuses to, and reports NaN instead.
print(df['Age'].mean())
print(df['Age'].mean(skipna=False))

**Question 3.** The cell above printed the mean of `Age` twice and got two different results, one of them `NaN`. Why do they differ, and which of the two would you report?

**Answer**

*Provide your answer here*

In [ ]:
# .describe() works on a single column too.
df['Age'].describe()

> Above I am using the `.` reference to access the column name as an attribute.  I can do this because the column name __does not have any spaces__ in the name.  As a rule, I tend to "clean" column names so that I can use this type of reference in my code, but in practice, there is no functional difference between `df['Age']` and `df.Age`

In [ ]:
# We are not limited to the mean -- type df.Age. and press Tab to see what else a column can do.
print(df.Age.min())
print(df.Age.max())
print(df.Age.median())

In [ ]:
# For categorical data, start with the list of distinct values.
df.Region.unique()

> Read that output carefully — `nan` is in the list. `.unique()` is the fastest way to see every distinct label a column actually contains, blanks included, and it is where you catch the near-duplicates (`NY` and `New York`, `Card` and `Cards`) that would otherwise split one group into two.

In [ ]:
# .nunique() counts the distinct values instead of listing them.
df.Region.nunique()

<img src="https://sharpsight.ai/wp-content/uploads/2021/07/pandas-value-counts_FEATURED-IMAGE.png" width="400">

In [ ]:
# .value_counts() counts the rows per category, sorted largest first.
df.Region.value_counts()

In [ ]:
# Missing values are excluded by default. dropna=False shows them, which is usually what you want.
df.Region.value_counts(dropna=False)

**Question 4.** The two `.value_counts()` tables above do not add up to the same number of respondents. Who is missing from the first one, and what does that do to a percentage built on it?

**Answer**

*Provide your answer here*

# Follow up Questions and Exercises — Part 3: summaries and aggregations

In [ ]:
# Starter code: read the workbook again and load just the Orders sheet.
orders = pd.read_excel(DATA + 'sales.xlsx', sheet_name='Orders')

orders.head(3)

**Exercise 10.** How many rows and columns are in the `orders` dataframe?

In [ ]:
# Your code here

**Answer**

*Provide your answer here*

**Exercise 11.** What is the average discount for the full dataset?

In [ ]:
# Your code here

**Answer**

*Provide your answer here*

**Exercise 12.** For each product category, show the frequency of each value.

In [ ]:
# Your code here

**Answer**

*Provide your answer here*

**Exercise 13.** Tricky! Can you adjust the values so instead of the counts, it's a percentage of the total?

> TIP: https://pandas.pydata.org/docs/reference/api/pandas.Series.value_counts.html

In [ ]:
# Your code here

**Answer**

*Provide your answer here*

## Row and Column Selection

In [ ]:
# Selecting a single column gives a Series, and everything we did above still applies to it.
df['Age'].tail(3)

In [ ]:
# .sample() draws random rows; random_state makes that draw repeatable.
df.Age.sample(3, random_state=42)

In [ ]:
# Pass a LIST of column names to keep several columns -- your Python fundamentals showing up again.
cols_to_keep = ['Age', 'Education']
df2 = df[cols_to_keep]

df2.head(3)

In [ ]:
# Confirm what you built: still a DataFrame, same rows, fewer columns.
print(type(df2))
print(df2.shape)

In [ ]:
# The list can be written inline, which is what you will see most often.
df[['Age', 'Education', 'Income']].head(3)

In [ ]:
# One bracket gives a Series, two brackets give a DataFrame -- a distinction that trips everyone up once.
print(type(df['Age']))
print(type(df[['Age']]))

**Why you care.** A Series has no column headers and cannot hold a second column, so `.merge()`, `.to_excel()` and most plotting calls expect a DataFrame. If pandas ever complains that a Series has no attribute you are sure exists, count your brackets first.

In [ ]:
# Rows are selected with a True/False test, applied to every row at once.
df[df.Age > 40]

In [ ]:
# The same idea on a text column. Watch the result count -- the file also contains a lowercase "no".
df[df.Recommend == 'Yes']

**Exercise 14.** The cell above kept the rows where `Recommend` is `'Yes'` and found 6 of them. Run the same filter for `'No'`, count the rows, then compare that count with `df.Recommend.value_counts(dropna=False)`. Do the two agree?

In [ ]:
# Your code here

**Answer**

*Provide your answer here*

In [ ]:
# .isin() checks membership in a list -- far cleaner than chaining several == conditions.
regions = ['Northeast', 'Midwest']
df[df['Region'].isin(regions)]

In [ ]:
# The tilde negates the expression: "region is NOT in that list".
df[~df['Region'].isin(regions)]

In [ ]:
# Rows and columns together: filter first, then hand the column list to the result.
df[df.Region == 'South'][cols_to_keep]

In [ ]:
# A cleaner way to say the same thing: .loc[row_filter, column_filter].
df.loc[df.Region == 'South', cols_to_keep]

> NOTE:  There are other ways to filter data in Pandas, but I generally teach these two methods because they are the most popular and I believe they support a mental model that is easier to understand in my opinion

# Follow up Questions and Exercises — Part 4: row and column selection

**Exercise 15.** How many rows in the `orders` dataset have a Unit Price greater than 100? Save the result as a new dataframe called `q1`.

In [ ]:
# Your code here

**Answer**

*Provide your answer here*

**Exercise 16.** For this filtered dataset, count the number of rows by Region.

In [ ]:
# Your code here

**Answer**

*Provide your answer here*

# Putting it all together!

**Exercise 17.** You are a sales analyst at an office supply company. The Sales Director wants to understand the total sales for each Region. Are the regions all performing the same, or are there some that may show signs of struggling based on this data?

HINT:  You may need to perform the same task a few times, but we covered everything that you need for this above!

This uses the orders data from the Sales workbook.

In [ ]:
# Your code here -- step 1: what regions are in the data, and are the labels clean?

In [ ]:
# Your code here -- step 2: total sales per region, and each region's share of the total

In [ ]:
# Your code here -- step 3: orders placed and average order value per region, then a chart

**Answer**

*Provide your answer here*

# Next Session: Cleaning

We answered the Sales Director's question, but look at what we walked past on the way.

- An `Age` of **148**, which sorting turned up in one line.
- A `Recommend` column that answers both `No` and `no`, so any count of one understates the other.
- Blanks in `Age`, `Satisfaction` and `Region`.

Every one of those is still in the file. Exploration finds problems; it does not fix them.

Session 4 is the fixing -- and, more to the point, defending each fix. "Clean the data" is never a
single command. It is a series of judgement calls, and every one of them changes the numbers you end
up reporting.