<a href="https://colab.research.google.com/github/elhamod/IS834_Fall_2026/blob/main/Session%2004%20-%20Pandas%20II%20-%20Cleaning%20and%20Preparation/04_Analytics_with_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# IS834 — Session 4

Work through this notebook in Colab. The lecture cells are filled in and ready to run; the
**Exercises** are yours to complete — write your code in the `# Your code here` cells and your
reasoning in the `*Provide your answer here*` cells.

Every dataset is read straight from the course repository, so there is nothing to upload or install.

*Adapted from Brock Tibert's IS834 Fall 2025 session 4. Edited for Fall 2026 by Mohannad Elhamod.*

# Learning Goals

Session 3 loaded an unfamiliar dataset and described what was in it. This session turns that
description into a decision: what is wrong with the file, and what are you going to do about it?

- Auditing a dataset for quality problems
- Feature engineering -- creating new columns from existing ones
- Removing and renaming columns
- Changing data types
- Replacing values, including bad values and outliers
- Handling missing data
- String transformations
- Categorical data, nominal and ordinal
- Duplicates, and why the obvious check misses them

Everything below assumes session 3's toolkit: `read_csv`, `.info()`, `.describe()`, `.unique()`,
`.value_counts()` and filtering with `df[df.column > value]`. Those are how we *find* the problems.
The new material is what happens next.

In [1]:
# pandas is the only package this notebook needs, and Colab already has it installed.
import pandas as pd

# Every data file this notebook uses is read straight from the course repository.
# There is nothing to upload: DATA is the folder those files live in.
DATA = "https://raw.githubusercontent.com/elhamod/IS834_Fall_2026/main/data/"

# Warmup Exercises

Five questions on last session's material, to get the loading-and-looking reflexes back before we
start changing anything.

**Exercise 1.** Read the diamonds dataset into a DataFrame called `diamonds` and look at the first few rows.

In [2]:
# Your code here
diamond = pd.read_csv(DATA+'diamonds.csv')
diamond

,rownames,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...,...
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

**Answer**

*Provide your answer here*

**Exercise 2.** How many rows and columns does the dataset have?

In [3]:
# Your code here
diamond.shape

(53940, 11)

**Answer**

*Provide your answer here*

**Exercise 3.** Retrieve the schema information for the dataset.

In [5]:
# Your code here
diamond.info()

<class 'pandas.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   rownames  53940 non-null  int64
 1   carat     53940 non-null  float64
 2   cut       53940 non-null  str
 3   color     53940 non-null  str
 4   clarity   53940 non-null  str
 5   depth     53940 non-null  float64
 6   table     53940 non-null  float64
 7   price     53940 non-null  int64
 8   x         53940 non-null  float64
 9   y         53940 non-null  float64
 10  z         53940 non-null  float64
dtypes: float64(6), int64(2), str(3)
memory usage: 4.5 MB

**Answer**

*Provide your answer here*

**Exercise 4.** Are there any missing values in the dataset?

In [6]:
# Your code here
diamond.isnull().sum()

rownames    0
carat       0
cut         0
color       0
clarity     0
depth       0
table       0
price       0
x           0
y           0
z           0
dtype: int64

**Answer**

*Provide your answer here*

**Exercise 5.** Return a random sample of 3 rows.

In [7]:
# Your code here
diamond.sample(3, random_state=100)

,rownames,carat,cut,color,clarity,depth,table,price,x,y,z
52264,52265,0.57,Ideal,E,VS2,61.5,57.0,2491,5.35,5.32,3.28
21073,21074,1.16,Ideal,G,VS1,61.5,55.0,9248,6.75,6.81,4.17
42161,42162,0.51,Ideal,G,SI1,63.2,58.0,1284,5.05,5.08,3.20

**Answer**

*Provide your answer here*

# Step 0: Audit Before You Clean

Cleaning is not a checklist you run. It is a set of decisions, and you cannot defend a decision you
made before you knew what was broken -- so the first thing we do is take an inventory of the damage.

The survey below is the same file we explored last session, freshly loaded and untouched.

In [8]:
# Reload last session's survey. Nothing here has been cleaned yet.
df = pd.read_csv(DATA + "sample-survey-data.csv")
df.head(3)

,id,Age,userid,Income,Education,Satisfaction,Recommend,Region,Signup Date,comment
0,1,23.0,user1,35000,Bachelor,4.0,Yes,Northeast,2025-05-01,Absolutely fantastic service — I am extremely ...
1,2,45.0,user2,-68000,Master,5.0,Yes,Midwest,2024-05-03,The product quality is excellent and the exper...
2,3,31.0,user3,42000,Associate,3.0,No,South,2024-04-09,I really enjoyed the fast delivery and friendl...

In [9]:
# Numeric problems hide in the min and max, not in the mean.
df[['Age', 'Income']].describe().T[['count', 'mean', 'min', 'max']]

        count          mean      min      max
Age      11.0     46.454545     23.0    148.0
Income   12.0  52303.583333 -68000.0  91000.0

> An age of **148** and an income of **-68,000**. Neither is possible, and both are already baked into
> the means printed right above them. The mean is the number people quote; the min and max are the
> numbers that tell you whether the mean is worth quoting.

In [10]:
df[['Age', 'Income']].describe().loc[['count', 'mean', 'min', 'max']]

              Age        Income
count   11.000000     12.000000
mean    46.454545  52303.583333
min     23.000000 -68000.000000
max    148.000000  91000.000000

In [11]:
# Text problems never reach describe() at all -- you have to list the labels yourself.
print(df.Region.unique())
print(df.Recommend.unique())

<StringArray>
['Northeast', 'Midwest', 'South', 'West', nan, 'North']
Length: 6, dtype: str
<StringArray>
['Yes', 'No', 'no', nan]
Length: 4, dtype: str

In [12]:
# dropna=False keeps the blanks in the table instead of quietly dropping them.
print(df.Region.value_counts(dropna=False))
print(df.Recommend.value_counts(dropna=False))

Region
South        3
West         3
Northeast    2
Midwest      2
NaN          1
North        1
Name: count, dtype: int64
Recommend
Yes    6
No     4
no     1
NaN    1
Name: count, dtype: int64

> `no` and `No` are the same answer recorded two ways, so a report counting `No` says 4 when the
> honest answer is 5 — two categories have quietly become three. And one respondent left `Region`
> blank, which is only visible because `dropna=False` kept the row in the table.

In [13]:
# How much is missing, and in which columns?
df.isna().sum()

id              0
Age             1
userid          0
Income          0
Education       0
Satisfaction    1
Recommend       1
Region          1
Signup Date     0
comment         0
dtype: int64

In [36]:
df[df.duplicated(['userid'])]
# df.shape
# df

,id,Age,userid,Income,Education,Satisfaction,Recommend,Region,Signup Date,comment
4,4,52.0,user4,91000,Doctorate,4.0,Yes,West,2025-01-02,"The product works fine, but I am slightly disa..."
11,11,25.0,user3,78643,High School,2.0,No,North,2026-02-10,This was the worst experience I’ve ever had — ...

In [37]:
# "Duplicate" depends on what you compare: whole rows, or the id meant to identify one person.
df_cleaned = df.drop_duplicates(['id'])
df_cleaned = df_cleaned[df_cleaned['Age'] < 120]
df_cleaned = df_cleaned[df_cleaned['Age'] > 0]
df_cleaned

,id,Age,userid,Income,Education,Satisfaction,Recommend,Region,Signup Date,comment
0,1,23.0,user1,35000,Bachelor,4.0,Yes,Northeast,2025-05-01,Absolutely fantastic service — I am extremely ...
1,2,45.0,user2,-68000,Master,5.0,Yes,Midwest,2024-05-03,The product quality is excellent and the exper...
2,3,31.0,user3,42000,Associate,3.0,No,South,2024-04-09,I really enjoyed the fast delivery and friendl...
3,4,52.0,user4,91000,Doctorate,4.0,Yes,West,2025-01-02,"Overall a good experience, though a few minor ..."
5,5,27.0,user5,50000,Bachelor,NaN,no,Northeast,2024-11-12,"It was okay — not amazing, not terrible, just ..."
6,6,38.0,user6,60000,Master,5.0,Yes,South,2023-05-14,"I am unhappy with the slow shipping, but custo..."
7,7,41.0,user7,72000,Bachelor,3.0,No,Midwest,2024-12-10,The experience was frustrating and somewhat di...
8,8,29.0,user8,40000,High School,4.0,NaN,West,2024-09-27,Very poor quality — I regret buying this produ...
11,11,25.0,user3,78643,High School,2.0,No,North,2026-02-10,This was the worst experience I’ve ever had — ...

In [38]:
df_cleaned = df.drop_duplicates(['id'])
df_cleaned = df_cleaned[(df_cleaned['Age'] < 120) | (df_cleaned['Age'] > 0)]
#df_cleaned = df_cleaned[df_cleaned['Age'] > 0]
df_cleaned

,id,Age,userid,Income,Education,Satisfaction,Recommend,Region,Signup Date,comment
0,1,23.0,user1,35000,Bachelor,4.0,Yes,Northeast,2025-05-01,Absolutely fantastic service — I am extremely ...
1,2,45.0,user2,-68000,Master,5.0,Yes,Midwest,2024-05-03,The product quality is excellent and the exper...
2,3,31.0,user3,42000,Associate,3.0,No,South,2024-04-09,I really enjoyed the fast delivery and friendl...
3,4,52.0,user4,91000,Doctorate,4.0,Yes,West,2025-01-02,"Overall a good experience, though a few minor ..."
5,5,27.0,user5,50000,Bachelor,NaN,no,Northeast,2024-11-12,"It was okay — not amazing, not terrible, just ..."
6,6,38.0,user6,60000,Master,5.0,Yes,South,2023-05-14,"I am unhappy with the slow shipping, but custo..."
7,7,41.0,user7,72000,Bachelor,3.0,No,Midwest,2024-12-10,The experience was frustrating and somewhat di...
8,8,29.0,user8,40000,High School,4.0,NaN,West,2024-09-27,Very poor quality — I regret buying this produ...
10,10,148.0,user10,80000,Master,5.0,Yes,South,2025-04-12,I am extremely dissatisfied and very disappoin...
11,11,25.0,user3,78643,High School,2.0,No,North,2026-02-10,This was the worst experience I’ve ever had — ...

In [39]:
df_cleaned.Recommend = df_cleaned.Recommend.replace('no', 'No')
print(df_cleaned.Recommend.value_counts(dropna=False))

Recommend
Yes    5
No     4
NaN    1
Name: count, dtype: int64

In [16]:
# for i in df_cleaned['Recommend']:
#     if i == 'no':
#         print(i)

**The audit, in one list.** Four blank answers (`Age`, `Satisfaction`, `Recommend` and `Region`), an
impossible age of 148, a negative income, a lowercase `no`, and — going by the last cell — a
respondent recorded twice that a whole-row comparison cannot see.

Summing booleans works here because Python counts `True` as 1, which is the trick that turns `.isna()`
from a table of True/False into a count.

The rest of this session is the toolkit for working through that list, and we come back to each item as
we reach the tool that fixes it. The duplicate is the one we leave for the exercises at the end,
because it is less about a command than about deciding what a row is supposed to represent.

# Feature Engineering

## New Columns

In [40]:
# Creating a column works exactly like adding a new key to a dictionary: name it, assign to it.
df['age2'] = df.Age * 2
df.head(3)

,id,Age,userid,Income,Education,Satisfaction,Recommend,Region,Signup Date,comment,age2
0,1,23.0,user1,35000,Bachelor,4.0,Yes,Northeast,2025-05-01,Absolutely fantastic service — I am extremely ...,46.0
1,2,45.0,user2,-68000,Master,5.0,Yes,Midwest,2024-05-03,The product quality is excellent and the exper...,90.0
2,3,31.0,user3,42000,Associate,3.0,No,South,2024-04-09,I really enjoyed the fast delivery and friendl...,62.0

In [41]:
# .insert() is the version that lets you choose WHERE the column goes: (position, name, values).
df.insert(2, 'age_in_months', df.Age * 12)
df.head(3)

,id,Age,age_in_months,userid,Income,Education,Satisfaction,Recommend,Region,Signup Date,comment,age2
0,1,23.0,276.0,user1,35000,Bachelor,4.0,Yes,Northeast,2025-05-01,Absolutely fantastic service — I am extremely ...,46.0
1,2,45.0,540.0,user2,-68000,Master,5.0,Yes,Midwest,2024-05-03,The product quality is excellent and the exper...,90.0
2,3,31.0,372.0,user3,42000,Associate,3.0,No,South,2024-04-09,I really enjoyed the fast delivery and friendl...,62.0

In [42]:
# del removes a column we no longer want -- that one was just a demonstration.
del df['age_in_months']
df.head(3)

,id,Age,userid,Income,Education,Satisfaction,Recommend,Region,Signup Date,comment,age2
0,1,23.0,user1,35000,Bachelor,4.0,Yes,Northeast,2025-05-01,Absolutely fantastic service — I am extremely ...,46.0
1,2,45.0,user2,-68000,Master,5.0,Yes,Midwest,2024-05-03,The product quality is excellent and the exper...,90.0
2,3,31.0,user3,42000,Associate,3.0,No,South,2024-04-09,I really enjoyed the fast delivery and friendl...,62.0

In [43]:
# Columns can be combined with each other -- income per year of age.
df['inc_age'] = df.Income / df.Age
df[['Age', 'Income', 'inc_age']].head(3)

    Age  Income      inc_age
0  23.0   35000  1521.739130
1  45.0  -68000 -1511.111111
2  31.0   42000  1354.838710

> Look at row 2: the income is −68,000, so `inc_age` is negative too. **Bad data does not stay in its own column.** Every feature you build on top of a dirty value inherits the problem, which is why cleaning comes before feature engineering in any real workflow.

In [44]:
# String methods work on a column through the .str accessor.
df['edu_len'] = df.Education.str.len()
df[['Education', 'edu_len']].head(3)

   Education  edu_len
0   Bachelor        8
1     Master        6
2  Associate        9

> `.str` is the bridge between "one piece of text" and "a whole column of text". Anything you can do to a Python string — `.upper()`, `.strip()`, `.replace()`, `.contains()` — has a `.str` version that does it to every row at once.

# Follow up Questions and Exercises — Part 1: new columns

In [87]:
# We use the diamonds dataset from the warmup exercise at the start of class.
# Reading it again here means this cell works whether or not you ran that exercise.
diamonds = pd.read_csv(DATA + "diamonds.csv")
diamonds.head(3)

,rownames,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31

**Exercise 6.** Create a new column holding the purchase price, which is 80% of the `price` column.

In [88]:
diamonds['price80'] = (diamonds['price'] * 0.8).round(2)
diamonds[['price', 'price80']]

       price  price80
0        326    260.8
1        326    260.8
2        327    261.6
3        334    267.2
4        335    268.0
...      ...      ...
53935   2757   2205.6
53936   2757   2205.6
53937   2757   2205.6
53938   2757   2205.6
53939   2757   2205.6

[53940 rows x 2 columns]

**Answer**

*Provide your answer here*

**Exercise 7.** Calculate the price per carat for each row and store it in a new column.

In [89]:
# Your code here
diamonds['price_per_carat'] = (diamonds['price'] / diamonds['carat']).round(2)
diamonds[['price', 'carat', 'price_per_carat']].head()

   price  carat  price_per_carat
0    326   0.23          1417.39
1    326   0.21          1552.38
2    327   0.23          1421.74
3    334   0.29          1151.72
4    335   0.31          1080.65

**Answer**

*Provide your answer here*

**Exercise 8.** Summarise the new price-per-carat column, and pull out its median.

In [90]:
# Your code here
diamonds.price_per_carat.describe().loc['50%'].round(2)

np.float64(3495.2)

**Answer**

*Provide your answer here*

**Exercise 9.** Create a new column holding the `cut` values in upper case.

In [91]:
# Your code here
diamonds['upper_cut'] = diamonds['cut'].str.upper()
diamonds[['cut', 'upper_cut']].head()

       cut upper_cut
0    Ideal     IDEAL
1  Premium   PREMIUM
2     Good      GOOD
3  Premium   PREMIUM
4     Good      GOOD

**Answer**

*Provide your answer here*

## Remove Columns

In [92]:
# The fast approach for a single column -- remember dictionaries.
del diamonds['rownames']
diamonds.head(3)

,carat,cut,color,clarity,depth,table,price,x,y,z,price80,price_per_carat,upper_cut
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,260.8,1417.39,IDEAL
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,260.8,1552.38,PREMIUM
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,261.6,1421.74,GOOD

In [93]:
# The other way is .drop with the columns argument, which takes a list of column names.
diamonds = diamonds.drop(columns=['table', 'z'])
diamonds.head(3)

,carat,cut,color,clarity,depth,price,x,y,price80,price_per_carat,upper_cut
0,0.23,Ideal,E,SI2,61.5,326,3.95,3.98,260.8,1417.39,IDEAL
1,0.21,Premium,E,SI1,59.8,326,3.89,3.84,260.8,1552.38,PREMIUM
2,0.23,Good,E,VS1,56.9,327,4.05,4.07,261.6,1421.74,GOOD

> `.drop()` returns a **new** DataFrame; it does not change `diamonds` unless you assign the result back, which is why the line starts with `diamonds = `. Forgetting that assignment — and then wondering why the column is still there — is one of the most common pandas mistakes.

## Rename columns

In [96]:
# Back to our small dataset.
df.head(3)

,id,age,userid,Income,Education,Satisfaction,Recommend,Region,Signup Date,comment,age2,inc_age,edu_len
0,1,23.0,user1,35000,Bachelor,4.0,Yes,Northeast,2025-05-01,Absolutely fantastic service — I am extremely ...,46.0,1521.739130,8
1,2,45.0,user2,-68000,Master,5.0,Yes,Midwest,2024-05-03,The product quality is excellent and the exper...,90.0,-1511.111111,6
2,3,31.0,user3,42000,Associate,3.0,No,South,2024-04-09,I really enjoyed the fast delivery and friendl...,62.0,1354.838710,9

In [97]:
# .rename with columns= and a dictionary of {old_name: new_name}.
df = df.rename(columns={'Age': 'age'})
df.head(3)

,id,age,userid,Income,Education,Satisfaction,Recommend,Region,Signup Date,comment,age2,inc_age,edu_len
0,1,23.0,user1,35000,Bachelor,4.0,Yes,Northeast,2025-05-01,Absolutely fantastic service — I am extremely ...,46.0,1521.739130,8
1,2,45.0,user2,-68000,Master,5.0,Yes,Midwest,2024-05-03,The product quality is excellent and the exper...,90.0,-1511.111111,6
2,3,31.0,user3,42000,Associate,3.0,No,South,2024-04-09,I really enjoyed the fast delivery and friendl...,62.0,1354.838710,9

In [98]:
# The dictionary can hold as many renames as you like.
df = df.rename(columns={'Income': 'inc', 'Region': 'reg'})
df.head(3)

,id,age,userid,inc,Education,Satisfaction,Recommend,reg,Signup Date,comment,age2,inc_age,edu_len
0,1,23.0,user1,35000,Bachelor,4.0,Yes,Northeast,2025-05-01,Absolutely fantastic service — I am extremely ...,46.0,1521.739130,8
1,2,45.0,user2,-68000,Master,5.0,Yes,Midwest,2024-05-03,The product quality is excellent and the exper...,90.0,-1511.111111,6
2,3,31.0,user3,42000,Associate,3.0,No,South,2024-04-09,I really enjoyed the fast delivery and friendl...,62.0,1354.838710,9

> Renaming to short lowercase names without spaces is not just taste: it is what lets you write `df.age` instead of `df['Signup Date']`, and it is why almost every analyst's first line after loading a file is a column-name cleanup.

## Change Data Types

In [99]:
# Check the schema before changing anything.
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            12 non-null     int64
 1   age           11 non-null     float64
 2   userid        12 non-null     str
 3   inc           12 non-null     int64
 4   Education     12 non-null     str
 5   Satisfaction  11 non-null     float64
 6   Recommend     11 non-null     str
 7   reg           11 non-null     str
 8   Signup Date   12 non-null     str
 9   comment       12 non-null     str
 10  age2          11 non-null     float64
 11  inc_age       11 non-null     float64
 12  edu_len       12 non-null     int64
dtypes: float64(4), int64(3), str(6)
memory usage: 1.3 KB

In [100]:
# .astype() converts a column to a different type.
df['inc_float'] = df.inc.astype(float)
df[['inc', 'inc_float']].head(3)

     inc  inc_float
0  35000    35000.0
1 -68000   -68000.0
2  42000    42000.0

In [101]:
# Converting a column that contains missing values to plain int fails. We catch the error so we can read it.
try:
    df['age_int'] = df.age.astype(int)
except Exception as error:
    print(type(error).__name__)
    print(error)

IntCastingNaNError
Cannot convert non-finite values (NA or inf) to integer.Replace or remove non-finite values or cast to an integer typethat supports these values (e.g. 'Int64')

In [102]:
# 'Int64' with a capital I is a nullable integer type -- it can hold whole numbers AND missing values.
df['age_int'] = df.age.astype('Int64')
df[['age', 'age_int']].head()

    age  age_int
0  23.0       23
1  45.0       45
2  31.0       31
3  52.0       52
4  52.0       52

**Why the error, and why the capital I?** Plain `int` is a NumPy type with no concept of "missing" — every slot must hold a number, so a single blank age makes the conversion impossible. `'Int64'` is pandas' own nullable integer type, which reserves a slot for `<NA>`. The lowercase/uppercase difference is genuinely load-bearing here, and it is exactly the kind of question worth handing to an AI assistant when the error message alone does not click.

> Dates have a conversion of their own, `pd.to_datetime`, which we come back to further down. But the error above is a good excuse to talk about replacing values first.

## Replace Values

In [103]:
# The starting point for this section.
df.head()

,id,age,userid,inc,Education,Satisfaction,Recommend,reg,Signup Date,comment,age2,inc_age,edu_len,inc_float,age_int
0,1,23.0,user1,35000,Bachelor,4.0,Yes,Northeast,2025-05-01,Absolutely fantastic service — I am extremely ...,46.0,1521.739130,8,35000.0,23
1,2,45.0,user2,-68000,Master,5.0,Yes,Midwest,2024-05-03,The product quality is excellent and the exper...,90.0,-1511.111111,6,-68000.0,45
2,3,31.0,user3,42000,Associate,3.0,No,South,2024-04-09,I really enjoyed the fast delivery and friendl...,62.0,1354.838710,9,42000.0,31
3,4,52.0,user4,91000,Doctorate,4.0,Yes,West,2025-01-02,"Overall a good experience, though a few minor ...",104.0,1750.000000,9,91000.0,52
4,4,52.0,user4,91000,Doctorate,4.0,Yes,West,2025-01-02,"The product works fine, but I am slightly disa...",104.0,1750.000000,9,91000.0,52

In [105]:
# Replace values inside one column. The shape is {"column-name": {"old-value": "new-value"}}.
df = df.replace({"Education": {"Master": "Masters~~~"}})
df.head(3)

,id,age,userid,inc,Education,Satisfaction,Recommend,reg,Signup Date,comment,age2,inc_age,edu_len,inc_float,age_int
0,1,23.0,user1,35000,Bachelor,4.0,Yes,Northeast,2025-05-01,Absolutely fantastic service — I am extremely ...,46.0,1521.739130,8,35000.0,23
1,2,45.0,user2,-68000,Masters~~~,5.0,Yes,Midwest,2024-05-03,The product quality is excellent and the exper...,90.0,-1511.111111,6,-68000.0,45
2,3,31.0,user3,42000,Associate,3.0,No,South,2024-04-09,I really enjoyed the fast delivery and friendl...,62.0,1354.838710,9,42000.0,31

In [106]:
# For a quick single change, work on the column directly with .replace(old, new).
df['Recommend'] = df['Recommend'].replace('Yes', 'Heck yeah')
df.Recommend.value_counts(dropna=False)

Recommend
Heck yeah    6
No           4
no           1
NaN          1
Name: count, dtype: int64

In [108]:
# Now the same tool on a real defect: undo the joke and fold the lowercase "no" into "No".
df['Recommend'] = df['Recommend'].replace({'Heck yeah': 'Yes', 'no': 'No'})
df.Recommend.value_counts(dropna=False)

Recommend
Yes    6
No     5
NaN    1
Name: count, dtype: int64

**This is the point of the section.** Before that line the column held four distinct answers — `Yes`, `No`, `no` and a blank — so counting "No" gave 4 when the honest answer was 5. Two categories had quietly become three. Standardising the spelling *before* you count is not tidying — it is the difference between a right answer and a wrong one.

In [109]:
# Same reasoning for the impossible age of 148 -- flag it as missing rather than keep it.
df.loc[df.age > 120, 'age'] = pd.NA
df.age.describe()

count    10.000000
mean     36.300000
std      10.883729
min      23.000000
25%      27.500000
50%      34.500000
75%      44.000000
max      52.000000
Name: age, dtype: float64

In [122]:
df.loc[df.age == pd.NA]

Empty DataFrame
Columns: [id, age, userid, inc, Education, Satisfaction, Recommend, reg, Signup Date, comment, age2, inc_age, edu_len, inc_float, age_int]
Index: []

In [123]:
# And the negative income, which cannot be right either.
df.loc[df.inc < 0, 'inc'] = pd.NA
df.inc.describe()

count       11.000000
mean     63240.272727
std      20403.598722
min      35000.000000
25%      46000.000000
50%      60000.000000
75%      79321.500000
max      91000.000000
Name: inc, dtype: float64

> The mean age drops from 46.5 to 36.3 once that single 148 is removed, and mean income rises from about \$52,300 to \$63,200 once the negative value goes. **One bad row out of twelve moved the headline number by 10 years.** That is why the min/max line of `describe()` is worth reading before anything else.

In [124]:
# When we have missing values we can use fillna. First, see where they are.
df.isna().sum()

id              0
age             2
userid          0
inc             1
Education       0
Satisfaction    1
Recommend       1
reg             1
Signup Date     0
comment         0
age2            1
inc_age         1
edu_len         0
inc_float       0
age_int         1
dtype: int64

In [125]:
# Filling missing ages with -1 -- a common "placeholder" pattern.
df['age_clean'] = df.age.fillna(-1)
print(df.age_clean.tolist())
print('mean of age_clean:', df.age_clean.mean())

[23.0, 45.0, 31.0, 52.0, 52.0, 27.0, 38.0, 41.0, 29.0, -1.0, -1.0, 25.0]
mean of age_clean: 30.083333333333332

**And there is the trap.** −1 is a perfectly good number as far as pandas is concerned, so it goes straight into the average and drags it down. A placeholder only works if every later calculation knows to exclude it — and nothing in the code says so.

In [126]:
# A more defensible fill: substitute the mean of the values we do have.
replacement_value = df.age.mean()
df['age_clean2'] = df.age.fillna(replacement_value)
print('replacement value:', round(replacement_value, 1))
print(df.age_clean2.round(1).tolist())

replacement value: 36.3
[23.0, 45.0, 31.0, 52.0, 52.0, 27.0, 38.0, 41.0, 29.0, 36.3, 36.3, 25.0]

**Question 1.** The cell above filled the missing ages with the column mean instead of with -1. What does that buy you, what does it cost, and when would you not do it?

**Answer**

*Provide your answer here*

# Follow up Questions and Exercises — Part 2: removing, renaming and replacing

In [151]:
diamonds = pd.read_csv(DATA + "diamonds.csv")

In [152]:
# Setup - we use the diamonds dataframe from earlier in class.
diamonds.head(3)

,rownames,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31

**Exercise 10.** Remove the `depth` column from `diamonds`.

In [153]:
# Your code here
diamonds = diamonds.drop(columns='depth')
diamonds

,rownames,carat,cut,color,clarity,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...
53935,53936,0.72,Ideal,D,SI1,57.0,2757,5.75,5.76,3.50
53936,53937,0.72,Good,D,SI1,55.0,2757,5.69,5.75,3.61
53937,53938,0.70,Very Good,D,SI1,60.0,2757,5.66,5.68,3.56
53938,53939,0.86,Premium,H,SI2,58.0,2757,6.15,6.12,3.74
53939,53940,0.75,Ideal,D,SI2,55.0,2757,5.83,5.87,3.64

**Answer**

*Provide your answer here*

**Exercise 11.** Rename the column `price` to `retail_price`.

In [154]:
# Your code here
diamonds = diamonds.rename(columns={'price':'retail_price'})
diamonds.head(3)

,rownames,carat,cut,color,clarity,table,retail_price,x,y,z
0,1,0.23,Ideal,E,SI2,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,65.0,327,4.05,4.07,2.31

**Answer**

*Provide your answer here*

**Exercise 12.** Replace the `cut` value `Good` with `meh`.

In [155]:
# Your code here
diamonds = diamonds.replace({'cut':{'Good':'Meh'}})
diamonds.head()

,rownames,carat,cut,color,clarity,table,retail_price,x,y,z
0,1,0.23,Ideal,E,SI2,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,61.0,326,3.89,3.84,2.31
2,3,0.23,Meh,E,VS1,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,58.0,334,4.20,4.23,2.63
4,5,0.31,Meh,J,SI2,58.0,335,4.34,4.35,2.75

In [149]:
diamonds = diamonds['cut'].replace({'Premium':'Miyum'})
diamonds.head()

0    Ideal
1    Miyum
2      Meh
3    Miyum
4      Meh
Name: cut, dtype: str

**Answer**

*Provide your answer here*

## Dates

`Signup Date` is still text, which is the loose end left at the end of the type-conversion section
above. Text sorts alphabetically, will not subtract, and cannot tell you a weekday.

In [156]:
# Dates arrive as text. pd.to_datetime converts them into real dates.
df['signup_date'] = pd.to_datetime(df['Signup Date'])
df[['Signup Date', 'signup_date']].dtypes

Signup Date               str
signup_date    datetime64[us]
dtype: object

In [157]:
df['Signup Date'][0]

'2025-05-01'

In [158]:
# Why bother? Because a real datetime can answer date questions for you, through the .dt accessor.
# df['dow_str'] = df.signup_date.dt.day_name()
df['dow_str'] = df.signup_date.dt.day_of_week
df['month'] = df.signup_date.dt.month_name()
df['year'] = df.signup_date.dt.year
df[['signup_date', 'dow_str', 'month', 'year']].head(3)

  signup_date  dow_str  month  year
0  2025-05-01        3    May  2025
1  2024-05-03        4    May  2024
2  2024-04-09        1  April  2024

> `.dt` is to dates what `.str` is to text: the bridge between one value and a whole column of them. Weekday, month name, quarter, "days since" — none of that is available while the column is still text.

## Categorical Data

This is how you tell pandas which columns are labels, not free text or numbers. Doing so saves memory, improves speed, keeps data clean, and can help with your downstream analytical tasks!  

It's not __always__ a step we have to do, but as a rule, properly setting each column's data type is a best practice.

![](https://media.geeksforgeeks.org/wp-content/uploads/20230918125039/2.png)

![](https://media.geeksforgeeks.org/wp-content/uploads/20230918125108/3.png)

In [167]:
# Re-load the small dataset into a fresh variable so the renames and fixes above do not confuse things.
df2 = pd.read_csv(DATA + "sample-survey-data.csv")
df2.sample(3)

,id,Age,userid,Income,Education,Satisfaction,Recommend,Region,Signup Date,comment
10,10,148.0,user10,80000,Master,5.0,Yes,South,2025-04-12,I am extremely dissatisfied and very disappoin...
0,1,23.0,user1,35000,Bachelor,4.0,Yes,Northeast,2025-05-01,Absolutely fantastic service — I am extremely ...
5,5,27.0,user5,50000,Bachelor,NaN,no,Northeast,2024-11-12,"It was okay — not amazing, not terrible, just ..."

In [168]:
# 1. categorical: "Region"
df2["region_cat"] = df2["Region"].astype("category")
df2.region_cat.dtype

CategoricalDtype(categories=['Midwest', 'North', 'Northeast', 'South', 'West'], ordered=False, categories_dtype=str)

**Question 2.** Is `Region` a nominal or an ordinal category?

**Answer**

*Provide your answer here*

In [169]:
# Now Satisfaction. First, what values are actually in there?
df2.Satisfaction.unique()

array([ 4.,  5.,  3., nan,  2.])

In [176]:
# pd.Categorical lets us state the categories AND their order.
df2["satis_cat"] = pd.Categorical(
    df2["Satisfaction"],
    categories=[1, 2, 3, 4, 5, 6],   # these could easily be strings, e.g. ['Bronze', 'Silver', 'Gold']
    ordered=True                  # this is the important part
)
df2.satis_cat.dtype

CategoricalDtype(categories=[1, 2, 3, 4, 5, 6], ordered=True, categories_dtype=int64)

In [177]:
df2[['Satisfaction',"satis_cat"]]

    Satisfaction satis_cat
0            4.0         4
1            5.0         5
2            3.0         3
3            4.0         4
4            4.0         4
5            NaN       NaN
6            5.0         5
7            3.0         3
8            4.0         4
9            2.0         2
10           5.0         5
11           2.0         2

In [178]:
df2.Satisfaction.value_counts(dropna=False)

Satisfaction
4.0    4
5.0    3
3.0    2
2.0    2
NaN    1
Name: count, dtype: int64

In [179]:
# Why bother? Because the values now stay in a meaningful order instead of an accidental one.
df2.satis_cat.value_counts(sort=False)

satis_cat
1    0
2    2
3    2
4    4
5    3
6    0
Name: count, dtype: int64

**Read the two tables side by side.** `value_counts()` on the raw column sorts by frequency, so the ratings come out in whatever order happens to be most common — useless for a chart. With `sort=False` on an ordered category, 1 through 5 appear in rating order, and **rating 1 shows up with a count of zero**. A plain `value_counts()` cannot show you a category that nobody chose, because it only knows about values that exist. Telling pandas the full set of valid categories is what makes the gap visible.

# Follow up Questions and Exercises — Part 3: categorical and date columns

**Exercise 13.** Turn `Education` into an ordinal categorical column, then count the rows per level.

In [202]:
# Your code here
df2.Education.unique()
df2['Edu_cat'] = pd.Categorical(df2['Education'], categories = ['High School','Associate','Bachelor', 'Master', 'Doctorate'], ordered=True)
# df2[['Education','Edu_cat']]
df2.Edu_cat.value_counts()

Edu_cat
Bachelor       4
Master         3
High School    2
Doctorate      2
Associate      1
Name: count, dtype: int64

In [206]:
df2.sort_values('Edu_cat')

,id,Age,userid,Income,Education,Satisfaction,Recommend,Region,Signup Date,comment,region_cat,satis_cat,Edu_cat
8,8,29.0,user8,40000,High School,4.0,NaN,West,2024-09-27,Very poor quality — I regret buying this produ...,West,4,High School
11,11,25.0,user3,78643,High School,2.0,No,North,2026-02-10,This was the worst experience I’ve ever had — ...,North,2,High School
2,3,31.0,user3,42000,Associate,3.0,No,South,2024-04-09,I really enjoyed the fast delivery and friendl...,South,3,Associate
0,1,23.0,user1,35000,Bachelor,4.0,Yes,Northeast,2025-05-01,Absolutely fantastic service — I am extremely ...,Northeast,4,Bachelor
5,5,27.0,user5,50000,Bachelor,NaN,no,Northeast,2024-11-12,"It was okay — not amazing, not terrible, just ...",Northeast,NaN,Bachelor
7,7,41.0,user7,72000,Bachelor,3.0,No,Midwest,2024-12-10,The experience was frustrating and somewhat di...,Midwest,3,Bachelor
9,9,NaN,user9,56000,Bachelor,2.0,No,NaN,2023-10-01,The service was terrible and the support team ...,NaN,2,Bachelor
1,2,45.0,user2,-68000,Master,5.0,Yes,Midwest,2024-05-03,The product quality is excellent and the exper...,Midwest,5,Master
6,6,38.0,user6,60000,Master,5.0,Yes,South,2023-05-14,"I am unhappy with the slow shipping, but custo...",South,5,Master
10,10,148.0,user10,80000,Master,5.0,Yes,South,2025-04-12,I am extremely dissatisfied and very disappoin...,South,5,Master
3,4,52.0,user4,91000,Doctorate,4.0,Yes,West,2025-01-02,"Overall a good experience, though a few minor ...",West,4,Doctorate
4,4,52.0,user4,91000,Doctorate,4.0,Yes,West,2025-01-02,"The product works fine, but I am slightly disa...",West,4,Doctorate

**Answer**

*Provide your answer here*

**Exercise 14.** Fix the datatype of `Signup Date` and extract the year into its own column.

In [213]:
# Your code here
df2['Signup Date'] = pd.to_datetime(df2['Signup Date'])
df2[['Signup Date']].dtypes

Signup Date    datetime64[us]
dtype: object

**Answer**

*Provide your answer here*

**Exercise 15.** Divide income by 12 and round the result to a whole number.

> TIP: `help(pd.Series.round)` tells you what the argument does.

In [219]:
# Your code here
# df2.columns
df2['monthly_income'] = (df2.Income / 12).round()
df2

,id,Age,userid,Income,Education,Satisfaction,Recommend,Region,Signup Date,comment,region_cat,satis_cat,Edu_cat,monthly_income
0,1,23.0,user1,35000,Bachelor,4.0,Yes,Northeast,2025-05-01,Absolutely fantastic service — I am extremely ...,Northeast,4,Bachelor,2917.0
1,2,45.0,user2,-68000,Master,5.0,Yes,Midwest,2024-05-03,The product quality is excellent and the exper...,Midwest,5,Master,-5667.0
2,3,31.0,user3,42000,Associate,3.0,No,South,2024-04-09,I really enjoyed the fast delivery and friendl...,South,3,Associate,3500.0
3,4,52.0,user4,91000,Doctorate,4.0,Yes,West,2025-01-02,"Overall a good experience, though a few minor ...",West,4,Doctorate,7583.0
4,4,52.0,user4,91000,Doctorate,4.0,Yes,West,2025-01-02,"The product works fine, but I am slightly disa...",West,4,Doctorate,7583.0
5,5,27.0,user5,50000,Bachelor,NaN,no,Northeast,2024-11-12,"It was okay — not amazing, not terrible, just ...",Northeast,NaN,Bachelor,4167.0
6,6,38.0,user6,60000,Master,5.0,Yes,South,2023-05-14,"I am unhappy with the slow shipping, but custo...",South,5,Master,5000.0
7,7,41.0,user7,72000,Bachelor,3.0,No,Midwest,2024-12-10,The experience was frustrating and somewhat di...,Midwest,3,Bachelor,6000.0
8,8,29.0,user8,40000,High School,4.0,NaN,West,2024-09-27,Very poor quality — I regret buying this produ...,West,4,High School,3333.0
9,9,NaN,user9,56000,Bachelor,2.0,No,NaN,2023-10-01,The service was terrible and the support team ...,NaN,2,Bachelor,4667.0
10,10,148.0,user10,80000,Master,5.0,Yes,South,2025-04-12,I am extremely dissatisfied and very disappoin...,South,5,Master,6667.0
11,11,25.0,user3,78643,High School,2.0,No,North,2026-02-10,This was the worst experience I’ve ever had — ...,North,2,High School,6554.0

**Answer**

*Provide your answer here*

## Numeric -> Categorical

In [220]:
# pd.cut slices a numeric column into bands. Here: three equal-width bands of income.
df2['income_bands'] = pd.cut(df2.Income, 3)
df2.income_bands.value_counts(sort=False)

income_bands
(-68159.0, -15000.0]     1
(-15000.0, 38000.0]      1
(38000.0, 91000.0]      10
Name: count, dtype: int64

**How to read those labels.** `(-15000.0, 38000.0]` means "greater than −15,000, up to and including 38,000" — a round bracket excludes the endpoint, a square bracket includes it.

**And look at the counts: 1, 1, 10.** `pd.cut` with a number splits the *range* into equal-width slices, and the range here runs from −68,000 to 91,000 because of the one impossible negative income. A single bad value has made two of the three bands almost empty and dumped 10 of 12 respondents into the third. The bands are useless.

**Exercise 16.** The bands above are useless because one impossible income stretched the range. Mark that value missing, band the column again, and give the three bands readable labels.

In [233]:
# Your code here
df2[df2['Income'] < 0] = pd.NA
df2.Income.describe()
df2.isna().sum()

id                1
Age               2
userid            1
Income            1
Education         1
Satisfaction      2
Recommend         2
Region            2
Signup Date       1
comment           1
region_cat        2
satis_cat         2
Edu_cat           1
monthly_income    1
income_bands      1
dtype: int64

**Answer**

*Provide your answer here*

# Mini Practice Problem

**Exercise 17.** Your firm has just begun to formally track and collect customer complaint data. The tracking system and process are new, so the data is not yet perfect.

You are an analyst supporting the customer service manager. The manager wants your help to understand the main sources of complaints and is looking for guidance on where to focus first.

Based on your analysis of the complaint data, what is your recommendation for where the manager should spend their time?

In [234]:
# Starter code: a list of dictionaries, which pd.DataFrame turns straight into a table.
data = [
    {"complaint_id": "C001", "category": "Card",    "description": "Charged twice",               "date_submitted": "2025-07-01", "tenure_months": 12},
    {"complaint_id": "C002", "category": "Cards",   "description": "Card not received",           "date_submitted": "2025-07-02", "tenure_months": 24},
    {"complaint_id": "C003", "category": "CRAD",    "description": "Card declined at POS",        "date_submitted": "2025-07-02", "tenure_months": None},
    {"complaint_id": "C004", "category": "ATM",     "description": "Cash not dispensed",          "date_submitted": "2025-07-03", "tenure_months": 6},
    {"complaint_id": "C005", "category": "atm",     "description": "Machine out of service",      "date_submitted": "2025-07-03", "tenure_months": 8},
    {"complaint_id": "C006", "category": "Loans",   "description": "Late fee dispute",            "date_submitted": "2025-07-04", "tenure_months": None},
    {"complaint_id": "C007", "category": "Loan",    "description": "Payment not applied",         "date_submitted": "2025-07-05", "tenure_months": 18},
    {"complaint_id": "C008", "category": "checking","description": "Unexpected monthly fee",      "date_submitted": "2025-07-06", "tenure_months": 3},
    {"complaint_id": "C009", "category": "Checking","description": "Overdraft fee issue",         "date_submitted": "2025-07-06", "tenure_months": None},
    {"complaint_id": "C010", "category": "Mortg.",  "description": "Escrow analysis confusion",   "date_submitted": "2025-07-07", "tenure_months": 30},
    {"complaint_id": "C011", "category": "Mortgage","description": "Rate adjustment unclear",     "date_submitted": "2025-07-07", "tenure_months": 36},
    {"complaint_id": "C012", "category": "Card",    "description": "Lost card replacement delay", "date_submitted": "2025-07-08", "tenure_months": 5},
    {"complaint_id": "C013", "category": "ATM",     "description": "Deposit not posted",          "date_submitted": "2025-07-09", "tenure_months": None},
    {"complaint_id": "C014", "category": "Cards",   "description": "Incorrect card limit",        "date_submitted": "2025-07-10", "tenure_months": 20},
    {"complaint_id": "C015", "category": "Loan",    "description": "Prepayment penalty confusion","date_submitted": "2025-07-10", "tenure_months": 15},
]

complaints = pd.DataFrame(data)
complaints

,complaint_id,category,description,date_submitted,tenure_months
0,C001,Card,Charged twice,2025-07-01,12.0
1,C002,Cards,Card not received,2025-07-02,24.0
2,C003,CRAD,Card declined at POS,2025-07-02,NaN
3,C004,ATM,Cash not dispensed,2025-07-03,6.0
4,C005,atm,Machine out of service,2025-07-03,8.0
5,C006,Loans,Late fee dispute,2025-07-04,NaN
6,C007,Loan,Payment not applied,2025-07-05,18.0
7,C008,checking,Unexpected monthly fee,2025-07-06,3.0
8,C009,Checking,Overdraft fee issue,2025-07-06,NaN
9,C010,Mortg.,Escrow analysis confusion,2025-07-07,30.0
10,C011,Mortgage,Rate adjustment unclear,2025-07-07,36.0
11,C012,Card,Lost card replacement delay,2025-07-08,5.0
12,C013,ATM,Deposit not posted,2025-07-09,NaN
13,C014,Cards,Incorrect card limit,2025-07-10,20.0
14,C015,Loan,Prepayment penalty confusion,2025-07-10,15.0

In [235]:
# Your code here -- step 1: look before you leap (shape, types, missing values)
print(complaints.shape, "\n")
print(complaints.dtypes, "\n")
print(complaints.isna().sum())

(15, 5)

complaint_id          str
category              str
description           str
date_submitted        str
tenure_months     float64
dtype: object

complaint_id      0
category          0
description       0
date_submitted    0
tenure_months     4
dtype: int64

In [236]:
# Your code here -- step 2: count complaints by category, then clean the labels and count again
def clean_category(cat):
    if cat.category.startswith('C'):
        cat.category = 'Cards'  
    elif cat.category.startswith('M'):
        cat.category = 'Mortgage' 
    elif cat.category.startswith('a'):
        cat.category = 'ATM' 
    elif cat.category.startswith('L'):
            cat.category = 'Loan'
    elif cat.category.startswith('c'):
            cat.category = 'Checking'

    return cat.category

complaints['x'] = complaints.apply(clean_category, axis=1)


complaints.x.value_counts()

x
Cards       6
ATM         3
Loan        3
Mortgage    2
Checking    1
Name: count, dtype: int64

In [237]:
complaints.x.value_counts(normalize = True).round(2)

x
Cards       0.40
ATM         0.20
Loan        0.20
Mortgage    0.13
Checking    0.07
Name: proportion, dtype: float64

In [104]:
# Your code here -- step 3: turn the counts into shares, and check how usable tenure_months is
complaints.value_counts('category', normalize=True, sort=True)

category
ATM         0.133333
Card        0.133333
Cards       0.133333
Loan        0.133333
CRAD        0.066667
Checking    0.066667
Loans       0.066667
Mortg.      0.066667
Mortgage    0.066667
atm         0.066667
checking    0.066667
Name: proportion, dtype: float64

**Answer**

*Provide your answer here*

# Follow up Questions and Exercises — Part 4: auditing and duplicates

**Question 3.** `describe()` on the survey data ignored `userid`, `Education`, `Region`, `Recommend` and `comment`. What could go wrong if that summary were the only quality check you ran before reporting?

**Answer**

*Provide your answer here*

**Question 4.** We filled missing ages twice — once with −1 and once with the column mean. Both are defensible in some situation and indefensible in others. When is each one appropriate?

**Answer**

*Provide your answer here*

**Exercise 18.** The audit at the top found that `duplicated()` and `duplicated(subset='id')` disagree. Work out *which* respondent is duplicated, and why comparing whole rows misses it.

In [65]:
# Your code here

**Answer**

*Provide your answer here*

**Exercise 19.** A colleague suggests starting the analysis with `survey.dropna()`. Show what that costs on this dataset, and decide whether it is a good idea.

In [66]:
# Your code here

**Answer**

*Provide your answer here*

**Exercise 20.** The `userid` column looks like it should uniquely identify a person. Check whether it does, and work out what would happen if you de-duplicated on it.

In [67]:
# Your code here

**Answer**

*Provide your answer here*